spring:
  application:
    name: store-api
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpirationInSeconds: ${JWT_ACCESS_TOKEN_EXPIRATION_IN_SEC}
    refreshTokenExpirationInSeconds: ${JWT_REFRESH_TOKEN_EXPIRATION_IN_SEC}
  profiles:
    active: dev

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8081

stripe:
    secretKey: ${STRIPE_SECRET_KEY}
    webhookSecret: ${STRIPE_WEBHOOK_SECRET_KEY}
